// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh3OpMsUvcXlkbm7nwZ8dQN_643kfn7kI',
    appId: '1:722272389047:web:bf061ae750c778c13e8a32',
    messagingSenderId: '722272389047',
    projectId: 'planpals-a55de',
    authDomain: 'planpals-a55de.firebaseapp.com',
    storageBucket: 'planpals-a55de.appspot.com',
    measurementId: 'G-4K4LTGKTRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbRIHyEAsEVIRIG2yotN1tRDVo127ibyo',
    appId: '1:722272389047:android:3d1305c56c6374ff3e8a32',
    messagingSenderId: '722272389047',
    projectId: 'planpals-a55de',
    storageBucket: 'planpals-a55de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd43H8YjayvnUCDkUJ11ad9dn9NOHaPaw',
    appId: '1:722272389047:ios:fc8d97ba267d0cd83e8a32',
    messagingSenderId: '722272389047',
    projectId: 'planpals-a55de',
    storageBucket: 'planpals-a55de.appspot.com',
    iosBundleId: 'com.example.planpals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd43H8YjayvnUCDkUJ11ad9dn9NOHaPaw',
    appId: '1:722272389047:ios:fc8d97ba267d0cd83e8a32',
    messagingSenderId: '722272389047',
    projectId: 'planpals-a55de',
    storageBucket: 'planpals-a55de.appspot.com',
    iosBundleId: 'com.example.planpals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh3OpMsUvcXlkbm7nwZ8dQN_643kfn7kI',
    appId: '1:722272389047:web:0ad6b80c2190410f3e8a32',
    messagingSenderId: '722272389047',
    projectId: 'planpals-a55de',
    authDomain: 'planpals-a55de.firebaseapp.com',
    storageBucket: 'planpals-a55de.appspot.com',
    measurementId: 'G-QQSXE7B8NV',
  );

}